### ISSUE TITLE
Question: Best practices for dealing with named exports from modules

### ISSUE THREAD

**Issue by taion** [lodash/babel-plugin-lodash#116]
I have some exports in my entry point that look like:

```js
export { locationShape, routerShape } from './PropTypes'
```

https://github.com/reactjs/react-router/blob/v3.0.0-alpha.3/modules/index.js#L16

Will this work correctly with babel-plugin-lodash? If not, is there a way on my end to get it to work that still keeps tree-shaking working-ish between those two exports?

**Comment by jdalton** [comment]
Try it out. Play around with things and tinker with it.

**Comment by taion** [comment]
Got it. Looks like the way to go would be to use a subdirectory with something like `PropTypes/routerShape.js`.
