### ISSUE TITLE
Allow libraries to opt in to this transform

### ISSUE THREAD

**Issue by taion** [lodash/babel-plugin-lodash#117]
This is an half-baked thought – but, given the limitations of tree-shaking, would it make sense to augment the id handling behavior by allowing libraries to opt in to this transform in their `package.json` files?

It'd make it a bit easier to point users at this plugin – I'd just tell them to turn on the plugin, rather than turn on the plugin and then configure it as well.

I can benchmark the extra `package.json` loads if that would be useful.

**Comment by jdalton** [comment]
Sounds rad. Do you have a mockup of config names and all that?

**Comment by taion** [comment]
Not yet. Wanted to run this idea past first before thinking really hard about the name of a config key.

**Comment by jdalton** [comment]
If you get to it feel free to open a PR. You can reference this issue.
