### ISSUE TITLE
lodash is bundled in server-side build despite matching externals

### ISSUE THREAD

**Issue by ericclemmons** [lodash/babel-plugin-lodash#118]
My server-side build with Webpack, when using a config like this:

```js
{
  externals: /^@?\w[a-z\-0-9\./]+$/, // Matches valid npm packages
}
```

originally generated code similar to this:

```js
/***/ 8:
/***/ function(module, exports) {

module.exports = require("lodash");

/***/ },
```

(Notice how it's a blind pass-through to Node's `require` mechanism, as it matches the pattern in `externals`.

However, with `babel-plugin-lodash`, I've noticed the build size increased to include the source like this:

```js
/***/ "./node_modules/lodash/_arrayMap.js":
/***/ function(module, exports) {

/**
 * A specialized version of `_.map` for arrays without support for iteratee
 * shorthands.
 *
```

The build gets _smaller_ if I use `lodash-webpack-plugin`, but it appears that on a build where `target: "node"`, the module paths go from `lodash/_arrayMap.js` to `./node_modules/lodash/_arrayMap.js`, which means get bundled.

Unfortunately, the solution isn't usually as simple as "Well, don't use this plugin on the server, dummy!" because `.babelrc` is typically shared between both code-bases (and when sufficiently complex, is annoying to duplicate between all builds).

If this sounds like a problem to you too, let me know and I can find some time to create a test-case.

**Comment by jdalton** [comment]
Bring a repro/test-case my way and I'll get to fix'n it 😀

**Comment by jdalton** [comment]
Also interested in it converting it to `node_modules/lodash/_arrayMap.js` instead of `lodash/_arrayMap`

**Comment by jdalton** [comment]
After some thinking this looks like something tackled in the webpack config and not something a babel plugin can actually address. There's plenty of ways to toggle config based on environment.
