### ISSUE TITLE
Feature Request: Output errors when missing support flags

### ISSUE THREAD

**Issue by morsdyce** [lodash/babel-plugin-lodash#119]
I've been using this plugin along with the webpack plugin and came across an issue where I had code working in development but not in production builds.

The issue was that I was missing flags for currying and flattening.
Is it possible to detect cases where you are trying to use unsupported methods that need to be added via flags?

Maybe provide a deprecation function that will run and output the error to the console or in the best case fail the build with the missing flags.

Thanks!

**Comment by jdalton** [comment]
Hi @morsdyce!

Minifying shouldn't change the behavior. The `lodash-webpack-plugin` does have some detection when using methods like `_.flatten` directly. Other methods that use it internally to flatten arguments support passing an array of arguments, e.g. `_.curry([fn1, fn2])`.

**Comment by morsdyce** [comment]
I only applied this plugin in production mode as I assumed it would be a slow transformation I wouldn't need in development (I have no issue loading the full source locally).

I activated the plugin in development mode and the error displayed is very unclear:
`Uncaught (in promise) TypeError: Cannot read property 'length' of undefined`

Example code for triggering this:
```js
import { flow, map } from 'lodash/fp'

flow(
 map(item => item)
)({})
```

It would really be helpful if it could throw an error at least in development mode when the plugin is activated or throw compile errors when detecting such changes.

If this is not in your current priority I would like to hear if you'll be interested in this functionality so I could work on a pull request.

**Comment by jdalton** [comment]
You should use `flow([map(item=> item)])({})`.

**Comment by ngocketit** [comment]
Thanks @jdalton! That fixes the above error. However, I now get another one: `TypeError: Expected a function`. Following is the code:

```
import {map, flatten, sortBy, flow, uniq, filter} from 'lodash/fp'; 

var items = flow([
        map('items'),
        flatten(),
        sortBy('id'),
        uniq('id'),
        map(function(item) {
            return {
                id: item.id,
                title: item.title,
                description: item.description,
            };
        }),
        filter(hasWords)])(allItems);
```
What cloud I do wrong?

**Comment by ngocketit** [comment]
No worry. I figured it out. It's because I'm using `lodash-webpack-plugin` and property shorthand is not available. Thanks!

**Comment by jdalton** [comment]
@ngocketit it's not available by default. You can always enable the "shorthands" feature set though.
