### ISSUE TITLE
last is not defined when executed in Chrome devtools

### ISSUE THREAD

**Issue by tysonnero** [lodash/babel-plugin-lodash#123]
Hi,

If I import a lodash module as so: `import last from 'lodash/last';`
Then open up the Chrome devtoools consol and execute something like: `last(someArray)`
I get the following error: `Uncaught ReferenceError: last is not defined`

This happens for any imported module.
I have this plugin installed and `"plugins": ["lodash"]` in my .babelrc.
Any ideas what I'm doing wrong?

Thanks!

**Comment by jdalton** [comment]
Hi @tysonnero!

I can't repro the issue.

When I do:
```js
import last from 'lodash/last';

console.log(last([1,2,3]));

```
I get:
```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	'use strict';

	var _last = __webpack_require__(1);

	var _last2 = _interopRequireDefault(_last);

	function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

	console.log((0, _last2.default)([1, 2, 3]));

/***/ },
/* 1 */
/***/ function(module, exports) {

	/**
	 * Gets the last element of `array`.
	 *
	 * @static
	 * @memberOf _
	 * @since 0.1.0
	 * @category Array
	 * @param {Array} array The array to query.
	 * @returns {*} Returns the last element of `array`.
	 * @example
	 *
	 * _.last([1, 2, 3]);
	 * // => 3
	 */
	function last(array) {
	  var length = array ? array.length : 0;
	  return length ? array[length - 1] : undefined;
	}

	module.exports = last;


/***/ }
/******/ ]);
```

**Comment by tysonnero** [comment]
@jdalton Thanks for the quick response!

I may have worded that wrong. What I actually meant is if I set a break point, and try to execute `last([1,2,3])` in the Chrome devtools Console, I get the `last is not defined` error. I experienced this when trying to debug and didn't know if that was expected behavior or an actual issue.

Otherwise, it works flawlessly like you've modeled.

**Comment by jdalton** [comment]
Hmm, not sure. I can execute the compiled bundle without issue.

**Comment by DiscoNova** [comment]
I believe what you've described is the expected behaviour. The point of modules is that they don't leake their internal state ... even into the console (i.e. the console is not in same scope as the function execution - even when execution is paused by the debugger).

We can expose the internal state (through using console.log or a variable that gets assigned to global scope) but accessing the state from the outside is not possible.

For example's sake, if you do this in your module:

```
import x from 'y';
window.exposedX = x;
debugger;

```
...now you should have access to "exposedX" (because window is the default global scope) within the devtools console. I would strongly advise against doing anything like this in real life ;)

**Comment by tysonnero** [comment]
@DiscoNova Thanks for the explanation!
