### ISSUE TITLE
Cannot read property 'has' of undefined

### ISSUE THREAD

**Issue by alexanbj** [lodash/babel-plugin-lodash#124]
After deleting my node_modules today and reinstalling, and error is now thrown from babel-plugin-lodash:

```
Listening at http://localhost:3000
webpack built 6aa9794bf4359d8988c8 in 18297ms

ERROR in ./app/search/Search.jsx
Module build failed: TypeError: /Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/app/search/Search.jsx: Cannot read property 'has' of undefined
    at resolvePath (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-plugin-lodash/lib/importModule.js:26:24)
    at importModule (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-plugin-lodash/lib/importModule.js:38:25)
    at memoized (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/lodash/memoize.js:62:23)
    at /Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-plugin-lodash/lib/index.js:140:62
    at arrayEach (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/lodash/forEach.js:38:10)
    at /Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-plugin-lodash/lib/index.js:129:30
    at arrayEach (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/lodash/forEach.js:38:10)
    at /Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-plugin-lodash/lib/index.js:122:28
    at arrayEach (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/lodash/forEach.js:38:10)
    at PluginPass.Program (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-plugin-lodash/lib/index.js:112:26)
    at newFn (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-traverse/lib/visitors.js:301:19)
    at NodePath._call (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/alexanbj/Documents/Jobb/Prosjekter/KF/kvalitetsstyring/frontend/node_modules/babel-traverse/lib/path/context.js:48:17)
 @ ./app/search/routes.jsx 4:0-30
 @ ./app/routes.jsx
 @ ./app/index.jsx
 @ multi main
Child html-webpack-plugin for "index.html":
``` 
_Search.jsx_ uses the _debounce_ method from lodash: `import { debounce } from 'lodash';`

* babel-plugin-lodash: __3.2.8__
* lodash: __4.15.0__
* Node : __6.2.1__
* Env: OS X

.babelrc:
```
{
  "presets": ["react", ["es2015", {"modules": false}]],
  "plugins": [
    "lodash",
    "transform-object-rest-spread"
  ],
  "env": {
    "development": {
      "plugins": [
        "react-hot-loader/babel"
      ]
    }
  }
}
```

Edit: Added import statement from Search.jsx

**Comment by slestang** [comment]
Same issue here; all files doing something like:
```js
import { findIndex, result } from 'lodash'
```
throw an error.

- babel-plugin-lodash: the bug is reproducible with 3.2.6 to 3.2.8
- babel-core: 6.13.2
- lodash: 4.14.1
- Node : 4.2.6
- Env: Ubuntu 16.04

**Comment by jdalton** [comment]
@alexanbj Hmm I can't repro. Here is my results:
```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};

/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {

/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;

/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};

/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;

/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}


/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;

/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;

/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";

/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ function(module, exports) {

	import _debounce from 'lodash/debounce';


	_debounce(function () {}, 2);
	;

	(function () {
	  if (typeof __REACT_HOT_LOADER__ === 'undefined') {
	    return;
	  }
	})();

	;

/***/ }
/******/ ]);
```
lodash 4.15.0
node 6.3.1
webpack 1.13.1
babel-core 6.13.2
babel-loader 6.2.5
babel-plugin-transform-object-rest-spread 6.8.0
babel-preset-es2015 6.13.2
babel-preset-react 6.11.1
react-hot-loader 3.0.0-beta.2
babel-plugin-lodash 3.2.8

**Comment by slestang** [comment]
@jdalton I have the same package versions (apart for node & lodash) and I have the bug.

I think it came from https://github.com/lodash/babel-plugin-lodash/blob/master/src/ModuleCache.js#L24 where the glob function always return an empty array.
The parameter is /home/silvere/prog/my_project/node_modules/lodash/**/

The glob package version is 7.0.5 and minimatch is 3.0.3.

I try to create a matrix of working/not working version number but I couldn't make my build works anymore, even after rolling back to older version of babel, babel-preset, babel-loader...
I suppose that an sub-dependency change something but I cannot figure out which.

Do you have any idea how we could find what could be wrong?

**Comment by jdalton** [comment]
I tested with glob 7.0.5.

If you all could create a small repro that would rock.

**Comment by alexanbj** [comment]
I'll give it a go after work tomorrow, if it hasn't fixed itself in the meantime.

**Comment by slestang** [comment]
I re-did an
```
rm node_modules && npm install
```
and the bug seems to have disappear.

I compare all package versions between the buggy node_modules and the new one and ... there are no difference ... I give up trying to understand.

**Comment by DiscoNova** [comment]
Damn... had you done `npm prune` instead of `rm node_modules`, you would already know what leftover modules you had there hanging around ... now we might never know ;)

**Comment by DonCallisto** [comment]
@DiscoNova I have the same issue, maybe I can provide more informations? 
Let me know.

**Comment by dfoverdx** [comment]
I ran into this issue.  It looks like the compiled code is using `lodash_1.default.has` (or whatever member function) rather than `lodash_1.has`.  Changing my import from `import _ from 'lodash';` to `import * as _ from 'lodash';` seemed to help.  I'm still running into an error, but haven't figured out if it's related to lodash or not.

**Comment by IgorLesnevskiy** [comment]
I had the same problem, but in my case I solved it by renaming my working directory from `/myProject[v1]` to `myProject_v1`. It looks like the `[]` symbols are forbidden when you use `glob`.

**Comment by jairo-bc** [comment]
For those who came here with the same issue (even if the library is not maintained?)
Looks like the problem is in the working directory name. I had something like `~/projects/blabla+(6)+(1)-2.4.1`. Renamed to `~/projects/blabla.6.1.2.4.1` and the issue stopped appearing.
