### ISSUE TITLE
Move to the lodash org?

### ISSUE THREAD

**Issue by jdalton** [lodash/babel-plugin-lodash#13]
Hey @megawac!

I think this plugin is super valuable to the lodash community and since you're already a lodash contributor would you dig moving this to the lodash org?

**Comment by jdalton** [comment]
Btw this would close #1. As it would be the official lodash plugin :)

**Comment by megawac** [comment]
I'm open to this but would like to defer the migration for a bit

**Comment by jdalton** [comment]
It'd be rad if it could be before v4 so devs have an official option to handle tree-shaking. It'd also be rad if there was a small example of how to integrate into webpack/rollup bundles.

**Comment by jdalton** [comment]
Done :D
