### ISSUE TITLE
Bundle becomes bigger when using plugin.

### ISSUE THREAD

**Issue by eldh** [lodash/babel-plugin-lodash#131]
So, still not really sure what's going on here, but I'll try to give the best info I can.

Problem: My bundle becomes bigger, not smaller, when using  babel-plugin-lodash.

My webpack build produces two files: client.js and vendor.js (lodash is included in vendor.js).

client.js without plugin: 1 141 480 bytes unzipped, 249KB gzipped
client.js with plugin: 1 199 622 bytes unzipped, 312KB gzipped.
vendor.js without plugin: 548KB unzipped, 149KB gzipped
vendor.js with plugin: 479KB unzipped, 124KB gzipped

So vendor.js shrinks by 25KB with the plugin, but client.js eats that up and then some by growing 63KB.

According to the generated stats.json files, lodash takes up 5% of the build with plugin and 15% without the plugin, and this seems to be reflected in vendor.js.

My very uninformed guess, after looking at the generated bundle, is that the requires in the code are harder to gzip, because each lodash sub-module is required. 

There are 779 instances of `/lodash` in the plugin bundle, all referring directly to the function being imported at that specific point (i.e `lodash/_baseGet`, `lodash/find` etc) .
In the no-plugin bundle there are 203 instances of `/lodash` all from require calls to lodash/lodash.

Now, my question is if I can get around this somehow? I don't quite understand enough about what's going on here to see a way forward...

**Comment by jdalton** [comment]
Hi @eldh!

Make sure the lodash plugin is loaded as babel plugin, `plugins: ['lodash']` and not a `preset.
You should make sure you're using "lodash": "^4.15.0", (^4) and avoid the chaining syntax.
Also be sure to use the Webpack optimization plugins for module order and minification.

If you have a sample repo or something that could help pin point the problem.

**Comment by eldh** [comment]
Oh yeah, should have shared `.babelrc` too.

```
{
  "presets": ["es2015-loose", "react", "stage-2"],
  "plugins": [
    "lodash",
    "transform-decorators-legacy",
    "transform-proto-to-assign",
    "transform-class-properties",
    "syntax-object-rest-spread",
    "transform-object-rest-spread"
  ],
}
```

Using `"lodash": "^4.15.0",`.

**Comment by eldh** [comment]
Sorry I can't share the repo, as it's a private app. :(

**Comment by jdalton** [comment]
Can you share your `webpack.config.js` too and possibly the command you execute your build with?

**Comment by jdalton** [comment]
The repeat requires won't be a problem and the size cut by `lodash-webpack-plugin` tends to eat any of the webpack scaffolding costs.

**Comment by eldh** [comment]
Unfortunately the webpack setup is a bit complex, so hard to just copy/paste, but I'll try to post the gist of it.

```
{
    output: {
      filename: 'client.js',
      chunkFilename: '[name].chunk.js',
    },
    node: {
      fs: 'empty',
    },
    module: {
      loaders: [
        {test: /\.json$/, loader: 'json'},
        {test: /\.svg/, loaders: ['url?mimetype=image/svg+xml', `svgo?${svgoConfig}`]},
        {test: /\.png/, loader: 'url?mimetype=image/png'},
        {
          test: /\.jsx|\.js$/,
          exclude: /node_modules/,
          loaders: [
            `${require.resolve('babel-loader')}?cacheDirectory`,
            // require.resolve('eslint-loader'),
          ],
        },
      ],
    },

    resolve: {
      root: [path.resolve('./src')],
      extensions: ['', '.js', '.jsx', '.json'],
      modulesDirectories: ['node_modules', 'src'],
      fallback: path.join(__dirname, 'node_modules'),
    },

    resolveLoader: {
      root: [
        path.resolve('./node_modules'),
      ],
      fallback: path.join(__dirname, 'node_modules'),
    },


    plugins: [
      new webpack.NamedModulesPlugin(),
      new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',

        // (Give the chunk a different name)
        filename: 'vendor.common.[chunkhash].js',

        minChunks: Infinity,
        // (with more entries, this ensures that no other module
        //  goes into the vendor chunk)
      }),
      new StatsPlugin('stats.json', {
        chunkModules: true,
      }),
      new webpack.optimize.MinChunkSizePlugin({minChunkSize: 100000}),
      new webpack.optimize.UglifyJsPlugin({
        compressor: {
          warnings: false,
          screw_ie8: true,
        },
      }),
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: '"production"',
        },
        DEV: false,
      }),
      new ExtractTextPlugin('[name].[chunkhash].css'),
      new ManifestPlugin(),
      new webpack.optimize.OccurenceOrderPlugin(),
      new webpack.NoErrorsPlugin(),
    ],
}
```

**Comment by eldh** [comment]
As you see, not using LodashWebpackPlugin here. The problem remained the same with that enabled. I'll post numbers in a minute.

**Comment by eldh** [comment]
Actually, exactly same numbers when adding `new LodashWebpackPlugin()` to the plugins list, which is a bit surprising.

**Comment by jdalton** [comment]
Ya that doesn't sound right. It should be a pretty dramatic drop by including it. By it's nature it removes a lot of extra functionality to keep bundles small.

The `lodash-webpack-plugin` works by rewriting Lodash module paths. So if for some reason `babel-lodash-plugin` isn't kicking in or is kicking in less than it should then the impact of `lodash-webpack-plugin` will be reduced (it can't rewire if no modules are being used).

**Comment by jdalton** [comment]
For kicks add this to your `webpack.config.js` babel loader options:
```js
'query': {
  'plugins': ['lodash']
}
```
also why are you defining the loader as `require.resolve('babel-loader')`. That makes me think it's a path resolving issue.

**Comment by eldh** [comment]
Changing from `require.resolve('babel-loader')` to just `babel` did the trick! Had it in place to get some linked modules to work previously. Interesting that it would prevent the lodash plugin from kicking in. Thanks so much for the help, deeply appreciated!

**Comment by eldh** [comment]
Final score: vendor.js 120KB, client.js 250KB.

**Comment by jdalton** [comment]
Rock on :metal:!

Is that all gzipped? For size reporting I dig [gzip-size-cli](https://www.npmjs.com/package/gzip-size-cli) and [pretty-bytes-cli](https://www.npmjs.com/package/pretty-bytes-cli).
```js
webpack entry.js bundle.js && gzip-size bundle.js | pretty-bytes
```
