### ISSUE TITLE
Importing “each” actually brings “arrayEach”

### ISSUE THREAD

**Issue by WalterWeidner** [lodash/babel-plugin-lodash#132]
In our app we are using babel-plugin-lodash and lodash-webpack-plugin to only place specific lodash functions into our bundles when they are used inside bundle code.

One thing we have noticed is the each function always maps to the arrayEach implementation. This means that any calls that use each for objects are calling the wrong function and are not ran.

Is the configuration below incorrect? Is the usage inside of our bundle incorrect?

**webpack.config.js**

```
var LodashModuleReplacementPlugin = require('lodash-webpack-plugin');

module.exports = {
    entry: './src/entry.js',
    output: {
        filename: 'index.js',
        path: './dist'
    },
    module: {
      loaders: [
        { 
            test: /\.js$/, 
            exclude: /node_modules/, 
            loader: "babel-loader", 
            query: {
                plugins: ['lodash'],
                presets: ['es2015']
            }
        }
      ]
    },
    plugins: [
        new LodashModuleReplacementPlugin,
    ]
}
```
**entry.js**

```
import {each} from 'lodash';

each({name: 'Matt', age: 12}, function(item) {
    console.log('I don\'t get here', item);
});
```

**Comment by jdalton** [comment]
You're using `lodash-webpack-plugin` which disables collection support by default. 
Be sure to enable the "collections" [feature set](https://github.com/lodash/lodash-webpack-plugin#feature-sets).
```js
new LodashModuleReplacementPlugin({ 'collections': true })
```

**Comment by WalterWeidner** [comment]
@jdalton thank you so much! I totally missed that in your readme.
