### ISSUE TITLE
Add ability to pick lodash function dynamically

### ISSUE THREAD

**Issue by foxhound87** [lodash/babel-plugin-lodash#134]
I need to call `some` or `every` dynamically using a string.
For example, currently in my code I do: 

```javascript

$fn = x ? 'some' : 'every';

_[$fn](...);

```

right now, if I do it I get: 

`The 'lodash' method `$fn` is not a known module.`

**Comment by jdalton** [comment]
Hi @foxhound87!

That sounds incredibly complex to work out in a solid way.

**Comment by faceyspacey** [comment]
require them both and assign the functions statically as a variable and then choose which function to use.

```
import some from 'lodash/some'
import every from 'lodash/every'

let some = _.some
let every = _.every

$fn = x ? some : every;
```
