### ISSUE TITLE
The 'lodash' method `unionBy` is not a known module.

### ISSUE THREAD

**Issue by ElliotChong** [lodash/babel-plugin-lodash#149]
When attempting to use `unionBy` I'm receiving the following error:
```Module build failed: SyntaxError: The 'lodash' method `unionBy` is not a known module.```

Hopefully this isn't just a user mistake in configuration or something- will keep digging.

**Comment by jdalton** [comment]
Hi @ElliotChong!

Make sure you're using Lodash v4+.

**Comment by ElliotChong** [comment]
Thanks for the quick response @jdalton!

A version mismatch issue was my first debugging stop before filing an issue- Unfortunately I'm using `"lodash": "^4.17.2"` and `"babel-plugin-lodash": "^3.2.10"` which I believe are the latest on npm.

It's worth noting I've been using a slew of other `lodash` methods without issue and this only cropped up once I attempted to include `unionBy` in particular.

Finally- Thank you for `lodash`! 👍  :)

**Comment by jdalton** [comment]
@ElliotChong 

I can repro the issue. This
```js
import _ from 'lodash';
import { pickBy } from 'lodash';

const object = { 'a': 1, 'b': 2, 'c': 3 };

_.pickBy(object, v => v == 2);
pickBy(object, v => v == 2);
```
produces:
```
'use strict';

var _pickBy2 = __webpack_require__(16);

var _pickBy3 = _interopRequireDefault(_pickBy2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var object = { 'a': 1, 'b': 2, 'c': 3 };

(0, _pickBy3.default)(object, function (v) {
  return v == 2;
});
(0, _pickBy3.default)(object, function (v) {
  return v == 2;
});
```
