### ISSUE TITLE
Support other lodash builds

### ISSUE THREAD

**Issue by megawac** [lodash/babel-plugin-lodash#15]
It may be nice to support other lodash builds such as -compat and -es in transpilation. Currently these are simply ignored

**Comment by jdalton** [comment]
The `-compat` build is being dropped for v4.

**Comment by jdalton** [comment]
An es-to-es mode to transform
```js
import {map, reduce, filter} from 'lodash'
```
would rock.

**Comment by jdalton** [comment]
Support for `lodash-es` would rock!

**Comment by jdalton** [comment]
Closed via https://github.com/lodash/babel-plugin-lodash/commit/4b1ea1b784ddf98f1b07efd6425559593a9d1677.

**Comment by megawac** [comment]
No tests?

**Comment by megawac** [comment]
I'm pretty sure your patch doesn't work because `resolveModules` still
assumes `node_modules/lodash` is the base path

**Comment by jdalton** [comment]
No worries. I'll add tests in a bit.
