### ISSUE TITLE
File included from lodash/fp if missing in lodash

### ISSUE THREAD

**Issue by JorgenEvens** [lodash/babel-plugin-lodash#150]
When a lodash method does not exist at the root of the `lodash` package, it will be imported from the `lodash/fp` directory if it exists there. I would expect it to throw an error as usual for non-existing methods.

**Example:**
```js
import _ from 'lodash';

console.log(_.contains(['a'], 'a'));
```

Compiles to:
```js
var _contains2 = require('lodash/fp/contains');

var _contains3 = _interopRequireDefault(_contains2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

console.log((0, _contains3.default)(['a'], 'a'));
```

It seems that [this](https://github.com/lodash/babel-plugin-lodash/blob/3dc85918fb4c4be4a041c7ad1d9765afa1466b75/src/importModule.js#L12) line is causing the issue, but I have no idea what it is meant to be for.

**I am using:**
babel-cli v6.18.0
lodash v4.17.2
babel-plugin-lodash v3.2.10

**Comment by jdalton** [comment]
I could fix this with hardcoded logic for `fp` but I'm making the plugin more library generic.
There's no way to know that `lib.xyz` doesn't originate from `lib/fp/xyz`. This will no longer be a problem with Lodash [v5](https://github.com/lodash/lodash/wiki/Roadmap) when we separate the `fp` mixin from the primary package.
