### ISSUE TITLE
Potential Name Change?

### ISSUE THREAD

**Issue by jblock** [lodash/babel-plugin-lodash#154]
Hi! Got a...philosophical question for you? I think that's the right way to describe it:

I noticed that libraries like [`recompose`](https://github.com/acdlite/recompose#using-babel-lodash-plugin) and `ramda` work nicely with this plugin. Do you think it makes sense to explore changing the name of this utility to be a bit more generalized (rather than be centered around `lodash`)?

Feel free to shoot me down if this has already been brought up in other forums (or if you think this is a silly idea)--I couldn't find anything in the closed GH issues.

**Comment by jdalton** [comment]
Yep, that's [the plan](https://twitter.com/jdalton/statuses/756384733622173696).

Related #85, #122, #150

**Comment by sibelius** [comment]
check this out: https://bitbucket.org/amctheatres/babel-transform-imports
