### ISSUE TITLE
Webpack 2, CommonsChunkPlugin results in bigger bundle size

### ISSUE THREAD

**Issue by ngocketit** [lodash/babel-plugin-lodash#156]
Hi,

I'm using this plugin with Webpack 2.2.0 and its `CommonsChunkPlugin` and notice that the bundle size gets bigger. Here is `.babelrc` config:

```
{
    "plugins": [
        "lodash",
        ["transform-runtime", {
             "polyfill": false,
             "regenerator": true
        }]
    ],
    "presets": [
        ["es2015", {"modules": false}],
        "react",
        "stage-0"
    ]
}
```

Webpack is configured to split vendor libs in a common chunk:

```
entry: {
 vendors: [
      'react',
      'react-dom',
      'redux',
      'react-redux',
      'platform',
      'lodash',
      'urijs',
      'localforage',
      'core-js'
   ]
},

....
 new webpack.optimize.CommonsChunkPlugin({
       name: 'vendors',
       minChunks: function (module, count) {
             return (
                 module.resource && 
                 module.resource.indexOf(path.resolve('node_modules')) === 0
             );
       }
}),
```

With the plugin, in the `vendors` common chunk, `lodash` takes about 530KB (unminified and uncompressed). At the same time, `lodash` also ends up in other chunks with about only 40KB. 

Without the plugin, `vendors` remains the same, but there is no `lodash` in other chunks any more and the chunks are therefore a bit smaller.

So the question is: why does `lodash` take that big in the `vendors` chunk and why there is also smaller part of `lodash` which disappears if the plugin is not used, in other chunks? Am not using `lodash-webpack-plugin`.

**Comment by jdalton** [comment]
Hi @ngocketit!

I'm not sure. I''ve not used the common chunk plugin before. Lodash should only every be a max of ~24kb minified+gzipped. If you're not seeing that then chances are you may be multiple versions included in your bundle.
