### ISSUE TITLE
Is this needed with Webpack 2 stable?

### ISSUE THREAD

**Issue by andresgutgon** [lodash/babel-plugin-lodash#157]
## What?
Hi, first of all thank you for all your hard work. Is amazing all the effort you're putting on make lodash modular and produce smaller bundles.

I'm trying to understand Webpack 2 tree shaking. First my versions:
```
    "webpack": "2.2.1",
    "lodash": "^4.17.4",
```

With those options I'm trying this code:
``` javascript
// picking map
import _map from 'lodash/map';
const mapAdd = _map([1, 2, 3], (item) => item + 1);
console.log('result', mapAdd);

// All lodash universe
import _ from 'lodash';
const mapAdd = _.map([1, 2, 3], (item) => item + 1);
console.log('result', mapAdd);
```

## Results
Look at yellow line. Vendor bundle
#### Picking map
![image](https://cloud.githubusercontent.com/assets/49499/22625806/e4c9dda6-eb9e-11e6-89f7-04863351270a.png)

#### All lodash universe
![image](https://cloud.githubusercontent.com/assets/49499/22625810/fb490ade-eb9e-11e6-9151-fef380c9f90f.png)

It's pretty cool. Looks like some tree shaking is happening in my webpack 😄 

The thing is that I tried [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) putting this on my `.babelrc`: 
```
{
  "presets": [
    ["es2015", { "modules": false }],
    "react"
  ],
  "plugins": [
    "lodash",
    "...more"
  ]
}
```

But the results are the same. **Is that normal**?

Is important to highlight that `["es2015", { "modules": false }]` is fundamental to make tree shaking work on Webpack 2. Right?

**Comment by jdalton** [comment]
I don't know if it's still needed. It's easy enough for you to confirm it on your own though. Keep in mind your bundle reports are of the unminified ungzipped size.

**Comment by andresgutgon** [comment]
> I don't know if it's still needed

If you ask me I would say no. According to my results. For that reason I wanted to ask.
 
> Keep in mind your bundle reports are of the unminified ungzipped size.

Sorry, how this can affect the experiment? I mean, in both cases the bundle would be proportional smaller. 

Btw in case someone want to check my code is here: 
https://github.com/okonet/webpack-long-term-cache-demo/pull/7

Again thanks a lot for your work

**Comment by wmertens** [comment]
@jdalton I just tested this with webpack 2 in my app:

* lodash plugin: total size 195k
* `lodash: "lodash-es"` in webpack resolve alias: total size 198.7k
* no plugin or alias: 195k

(sizes are before minification)

So it seems that the plugin is indeed not needed? I do use `import {foo} from 'lodash'` everywhere.

**Comment by wmertens** [comment]
In fact, the size for lodash was smaller because some of my dependencies were loading lodash-es and it was added to the bundle as well. I get the smallest size by setting the alias `lodash: "lodash-es"` (198.7k). Setting `"lodash-es": "lodash"` gives 199.2k.

**Comment by wmertens** [comment]
Oops 💩 

I still had the plugin loading elsewhere :) Without the plugin, aliasing to lodash-es results in 608k, lodash in 693k. So the plugin is very much needed, but aliasing lodash to lodash-es seems like a good idea too.

**Comment by ConAntonakos** [comment]
To be clear with tree shaking, can you perform the following syntax?:

```
import {
  flatten,
  get,
  merge,
  orderBy,
  reduce,
} from 'lodash';
```

Do you need the `babel-plugin-lodash`, and do you need `lodash-es`? Thanks!

**Comment by jdalton** [comment]
You'll still need `babel-plugin-lodash` for `lodash` or `lodash-es`.

**Comment by ConAntonakos** [comment]
Thanks, @jdalton!

**Comment by exarus** [comment]
@jdalton So I want to get small builds of project with `lodash`, `Babel` and `Webpack 3`.

1)  is it sufficient to use lodash like this:
```js
import mean from 'lodash-es/mean'
```

2) Or it is OK to use lodash like this:
```js
import { mean } from 'lodash-es'
```

3) Or should I better use combo of these: `lodash-es`, `babel-plugin-lodash`, `lodash-webpack-plugin`.
