### ISSUE TITLE
Making clear that this plugin can be used for other libraries as well

### ISSUE THREAD

**Issue by 0x80** [lodash/babel-plugin-lodash#160]
I was surprised to find out from the [docs from recompose ](https://github.com/acdlite/recompose) that `babel-plugin-lodash` is not limited to Lodash at all. 

```javascript
{
  "plugins": [
       ["lodash", { id: ["lodash", "recompose"] }]
   ]
}
``` 

This allows you to write `import { compose, mapProps, withState } from 'recompose'`.

Wouldn't it make sense to rename this plugin to something more generic to avoid confusion, or at least mention this use-case in the readme?

**Comment by jdalton** [comment]
Dup of #159.
