### ISSUE TITLE
The 'lodash' method `omitBy` is not a known module

### ISSUE THREAD

**Issue by JeremyJonas** [lodash/babel-plugin-lodash#161]
When attempting to use omitBy I'm receiving the following error:
Module build failed: SyntaxError: The 'lodash' method `omitBy` is not a known module.

Seems like a duplicate of [#149](https://github.com/lodash/babel-plugin-lodash/issues/149) which was closed but not resolved.

**lodash** version *4.17.4*
**babel-plugin-lodash** version *3.2.11*

**Comment by jdalton** [comment]
I can't repro this issue. As with #149 make super sure you're using the latest Lodash:
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.omitBy = undefined;

var _omitBy2 = require('lodash/omitBy');

var _omitBy3 = _interopRequireDefault(_omitBy2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

exports.omitBy = _omitBy3.default;
```
