### ISSUE TITLE
Reverse functionality

### ISSUE THREAD

**Issue by teod** [lodash/babel-plugin-lodash#163]
I know it's weird, but I actually require in the project I'm working on the exact opposite functionality,
I'm importing my lodash modules like: 
```
import compose from 'lodash/fp/compose'
import debounce from 'lodash/debounce
```
And I want to have an output like:
```
import { compose } from 'lodash/fp'
import { debounce } from 'lodash' 
```

I want to improve the incremental build time during the development process using webpack DLL plugin, and unfortunately webpack keeps adding the lodash module into the bundle if I'm cherry picking lodash functions myself.

**Comment by jdalton** [comment]
This seems like a webpack support question.
Have you tried asking on the webpack slack channel?
