### ISSUE TITLE
rename to `babel-plugin-bundle-optimizer`?

### ISSUE THREAD

**Issue by mrtnbroder** [lodash/babel-plugin-lodash#164]
I've seen this plugin [so](https://github.com/neoziro/recompact) [many](https://github.com/acdlite/recompose) times now (I was about to link more packages, but I can't find more atm, LOL! but I saw it at a lot of packages), being used as a bundle optimizer that it should consider being renamed, to make more people aware of this plugin, and that it can help library authors optimize their libraries.

**Comment by jdalton** [comment]
Dup of #154.
