### ISSUE TITLE
 _.forOwn is not a function in template when use babel-plugin-lodash

### ISSUE THREAD

**Issue by grantCHG** [lodash/babel-plugin-lodash#165]
import _ from 'lodash';
_.template('<%\_.forOwn...%>')({ 'user': 'mustache' })

**Comment by jdalton** [comment]
Yep. Inspecting strings isn't such a doable thing. You can pass [an imports option](https://lodash.com/docs/#template) to `_.template`.
```js
_.template('<%_.forOwn...%>', { 'imports': { 'forOwn': _.forOwn } })({ 'user': 'mustache' })
```
