### ISSUE TITLE
Provide a default if pkg.main is missing

### ISSUE THREAD

**Issue by albertogasparin** [lodash/babel-plugin-lodash#173]
I was trying to use `babel-plugin-lodash` with [date-fns](https://github.com/date-fns/date-fns), however the plugin breaks badly because `date-fns` `package.json` does not have a `main` attribute.

Looking a the code, [it already handles](https://github.com/lodash/babel-plugin-lodash/blob/master/src/ModuleCache.js#L20) the case where `package.json` is missing. So, I'd like to propose to extend the check to the `main` attribute too, defaulting to `index.js` if missing so the plugin could be more resilient.

**Comment by jdalton** [comment]
👌 Would you be up for making a PR?

**Comment by albertogasparin** [comment]
Sure, will do
