### ISSUE TITLE
_createPartial is mistook as _createWrap

### ISSUE THREAD

**Issue by zation** [lodash/babel-plugin-lodash#177]
Please check this repo: https://github.com/zation/react-isomorphic-starter. Before I include babel-plugin-lodash and lodash-webpack-plugin, it works fine. After I include them, I get below error:

<img width="1033" alt="screen shot 2017-06-26 at 2 53 24 am" src="https://user-images.githubusercontent.com/1049425/27518798-a920ca36-5a1a-11e7-8aa8-0f7d9a936dcd.png">

You can reproduce it by command `npm start`.

I found `_createPartial.js` is bundled as `_createWrap.js`. Do I mistake anything?

**Comment by jdalton** [comment]
Hi @zation!

The `lodash-webpack-plugin` many disables [feature sets](https://github.com/lodash/lodash-webpack-plugin#feature-sets) by default so you have to opt-in to ones you want. Look at the `currying` or `metadata` feature set.

**Comment by zation** [comment]
Thanks! Fix it with `currying` option:

```js
    new LodashModuleReplacementPlugin({
      currying: true,
      paths: true,
    }),
```
