### ISSUE TITLE
`uniqBy` not a known module

### ISSUE THREAD

**Issue by casesandberg** [lodash/babel-plugin-lodash#181]
babel-plugin-lodash@3.2.11
lodash@4.17.4

```
Module build failed: SyntaxError: The 'lodash' method `uniqBy` is not a known module.
```

Reproduce:
```
_.uniqBy([2.1, 1.2, 2.3], Math.floor)
```

**Comment by jdalton** [comment]
Hi @casesandberg!

Can you double check that the version of Lodash it's transforming is v4.17.4. It detects method names by the actual files in the package so a misfire per the correct version is unlikely.
