### ISSUE TITLE
Method "_.get" returns undefined sometimes.

### ISSUE THREAD

**Issue by kmvan** [lodash/babel-plugin-lodash#182]
```javascript
import { get } from 'lodash'
const object = { 'a': [{ 'b': { 'c': 3 } }] }
console.log(get(object, 'a[0].b.c')) // output undefined
console.log(get(object, 'a')) // output object
console.log(get(object, 'a[0]')) // output undefined
```
Something wrong with my code?

**Comment by jdalton** [comment]
You're probably using this plugin with lodash-webpack-plugin and need to enable a feature set.

**Comment by kmvan** [comment]
Thank you man.
And which feature set?

**Comment by jdalton** [comment]
You most likely need to enable the `"paths"` feature set.

**Comment by kmvan** [comment]
Got it. https://github.com/lodash/lodash-webpack-plugin#feature-sets
