### ISSUE TITLE
Publish fix for missing main field.

### ISSUE THREAD

**Issue by knpwrs** [lodash/babel-plugin-lodash#190]
When I tried to use this module with [`uuid`](http://npm.im/uuid) I ran into an issue where `uuid` does not have a `main` field in its `package.json`. Looking at the commit history of this project it looks like the fix for this issue was pushed back in June but the fix was never published to npm. Just to confirm the fix works I tried using this repo in place of the version hosted on npm and it appears that everything is in working order. It would be great if the fix was deployed to npm so packages which do not have a `main` field could be used with this plugin.

**Comment by jdalton** [comment]
Ah nice! Glad to hear it fixed your problem.

I'm not in a hurry to bump another release. It will surely be updated before Lodash v5 lands.
