### ISSUE TITLE
Doesn't work in v7.0.0-beta.3 due to a breaking change

### ISSUE THREAD

**Issue by vlad-zhukov** [lodash/babel-plugin-lodash#193]
Ref: [beta.3 removed .metadata properties](https://github.com/babel/babel/pull/6343).

**Comment by jdalton** [comment]
Hi vald!

Are you up for doing a PR to fix it?

**Comment by vlad-zhukov** [comment]
Sorry, I don't have time right now to dig how it all works and what would be a fix for that.
