### ISSUE TITLE
Add test for dynamic lodash path resolution.

### ISSUE THREAD

**Issue by jdalton** [lodash/babel-plugin-lodash#20]
See https://github.com/megawac/babel-plugin-lodash/pull/18#issuecomment-169399786.

**Comment by megawac** [comment]
Easiest solution would be to test the plugin on both lodash@^3 and lodash@^4 as both work at the moment

**Comment by jdalton** [comment]
Closed by https://github.com/lodash/babel-plugin-lodash/commit/0ad8927822945928b5931a7fafc2f076035b0da0.
