### ISSUE TITLE
Cannot find module 'lodash-compat'

### ISSUE THREAD

**Issue by PengyuanZhao** [lodash/babel-plugin-lodash#201]
When I upgraded to the newest version 3.3.1, I got the error `Cannot find module 'lodash-compat'`. Any idea?

**Comment by jdalton** [comment]
The `lodash-compat` dep isn't used in the source of the project so I'm not sure where that's coming from. I can't repro the issue.

**Comment by rileylnapier** [comment]
i get this with node version 7.  i don't get it with node 6

![image](https://user-images.githubusercontent.com/7017640/32702277-8f69eec8-c799-11e7-824b-7d1a7a6025ce.png)

**Comment by specialkk** [comment]
I'm getting a similar and probably related issue with `lodash-es`. I believe it was fine before because the require call was wrapped in a try/catch but that was removed in 421468b. My Webpack setup is trying to include it even though it's a dev dependency and not actually needed.
