### ISSUE TITLE
Using v3.3.x with a custom id is not possible

### ISSUE THREAD

**Issue by neoziro** [lodash/babel-plugin-lodash#202]
Hello,

The commit 421468be621548b02601620393f39a57c54b344d broke the package. I explain:

- mapping.js is loaded by index.js
- mapping.js calls config()
- config iterates on default ids
- it tries to resolve lodash-compat
- lodash-compat is not found
- an error is thrown

It happens when we load index.js. I think reverting this commit is the best thing to do.

Thanks for this great package!

Also I think it should be specific to lodash but I use it for other packages. Do you know a good alternative to cherry-pick packages? The name is terrible when we use it for another package.

**Comment by jdalton** [comment]
Thanks for spotting the commit! Yep, I'll revert it, bump a patch release, then review the problem commit for a later release.

**Comment by jdalton** [comment]
Reverted https://github.com/lodash/babel-plugin-lodash/commit/1911ac755ba02b77e47f31bf4261286f8ef51985.

**Comment by neoziro** [comment]
@jdalton thanks!

**Comment by jdalton** [comment]
v3.3.2 is published :tada:
