### ISSUE TITLE
strange interaction with babel-plugin-istanbul

### ISSUE THREAD

**Issue by graingert** [lodash/babel-plugin-lodash#207]
https://github.com/istanbuljs/babel-plugin-istanbul/issues/116#issuecomment-347431770

> It might also be worthwhile to start a conversation on the babel-lodash plugin; have an extra set of eyes on the problem.

**Comment by jdalton** [comment]
Thanks for the heads up!

If you root cause anything don't hesitant to ping back. If the issue is on us we'll make it right.
