### ISSUE TITLE
Not reducing bundle size

### ISSUE THREAD

**Issue by deadcoder0904** [lodash/babel-plugin-lodash#209]
I've made a [repo](https://github.com/deadcoder0904/webpack-exam) demonstrating my problem.

It has `dist/vendor.min.js` which is generated using this plugin & gives a size of `30.1 kB gzip` while I am not using a lot of JavaScript. 

The expected bundle size must be around `5 kB gzip` but for me its a lot.

Anything that I've done wrong because I exactly followed the steps mentioned here ❓

**Comment by deadcoder0904** [comment]
Ok so quick update. `develop` branch on that repo has 1 change that made it reduce to `4 kB` & `585 B gzip` & the change that I've made is I've removed `CommonChunksPlugin`.

Is it possible to get it to work with `CommonChunksPlugin` & stripping off everything else ❓

**Comment by jdalton** [comment]
Hi @deadcoder0904!

I'm not sure. I'm not familiar with how `CommonChunksPlugin` interacts with others.

**Comment by deadcoder0904** [comment]
Cool no problem

**Comment by deadcoder0904** [comment]
Hey I solved it. Adding `minChunks` property & removing `entry.vendor` did the job 🎉

Solution in the repo https://github.com/deadcoder0904/webpack-exam
