### ISSUE TITLE
Is this plugin unnecessary if using webpack4?

### ISSUE THREAD

**Issue by marcofugaro** [lodash/babel-plugin-lodash#214]
With webpack4 if a library the flag `sideEffects: false` in its package.json, you're able to truly tree-shake the bundle.

Lodash [added it last december](https://github.com/lodash/lodash/pull/3533), so is this plugin unnecessary if using webpack4?

**Comment by jdalton** [comment]
Hi @marcofugaro!

Give it a try and report back 😋

**Comment by yamsellem** [comment]
Modular lodash is a really good initiative, but, with the release of webpack 4, I've having a hard time figuring what is the proper way to bundle an app without getting all lodash imports bundled in.

May you please consider adding a note (somewhere?) to detail what are your current recommandations?

Thanks a lot.
