### ISSUE TITLE
Poor typing handling

### ISSUE THREAD

**Issue by jeremejevs** [lodash/babel-plugin-lodash#215]
The following TypeScript code ...

```ts
import { template, TemplateExecutor } from "lodash";

const x: TemplateExecutor = template('')
```

... results in `The 'lodash' method 'TemplateExecutor' is not a known module`, in both `3.3.2` and the current master, `3.3.3-pre`.

### Research

Both `@babel/plugin-transform-flow-strip-types` and `@babel/plugin-transform-typescript` remove the typing imports in `visitor.ImportDeclaration`, as seen [here](https://github.com/babel/babel/blob/5166eef103fd18bbb3f498cbf7065866d9c1ea83/packages/babel-plugin-transform-typescript/src/index.js#L38-L71), while `babel-plugin-lodash` goes through the imports in `visitor.Program`, as seen [here](https://github.com/lodash/babel-plugin-lodash/blob/3832b150216517705a8b8c081519d07aa4411689/src/index.js#L55-L148).

Problem is, Babel doesn't execute plugins completely sequentially ([quick primer, with more details](https://jamie.build/babel-plugin-ordering.html)). Instead, it goes through the AST node-by-node, and invokes `visitor.*` for each node type it encounters, in each plugin, in the order they're defined. `visitor.Program` gets called before `visitor.ImportDeclaration`, since it's higher up the AST, so this plugin gets the imports as-is, without any type stripping, regardless of the plugin ordering in `.babelrc`.

It looks like this plugin is aware of the above, but doesn't address it properly. The `master` has a heuristic similar to what `@babel/plugin-transform-typescript` has, but it's missing the crucial `isImportTypeOnly` check (which would take care of `TemplateExecutor`), and Flow isn't handled at all. In the meanwhile, the [currently-released version](https://github.com/lodash/babel-plugin-lodash/blob/a253c12af0e1ebe2be4db58071aca2b321a061b0/src/index.js#L145-L148) is similar to [`@babel/plugin-transform-flow-strip-types`](https://github.com/babel/babel/blob/5166eef103fd18bbb3f498cbf7065866d9c1ea83/packages/babel-plugin-transform-flow-strip-types/src/index.js#L36-L51), but it doesn't handle `import type/typeof { something } from 'foo'` and `import { typeof something } from 'foo'` correctly, and it isn't able to handle TypeScript at all.

### Solution

A potential fix is probably to move as much logic to `visitor.ImportDeclaration.exit` as possible, so it gets executed **after** all plugins have run their `visitor.ImportDeclaration` (AKA `visitor.ImportDeclaration.enter`). However, I'm not sure if `exit` doesn't get called if its node got previously removed in an `enter`.

An alternative fix would be to fully replicate the type-stripping logic, but that's WET and prone to become broken over time.

Just in case, I have never dealt with Babel internals before, so don't take my words at face value.

**Comment by jdalton** [comment]
Hi @jeremejevs!

If you're up for a PR that would be great. You could also just use `lodash-es` with webpack 4 to get cherry-picking without `babel-plugin-lodash`.

**Comment by jeremejevs** [comment]
Hi @jdalton!

Thanks for the suggestion, but I can't do that because I want to use `lodash/fp`, and I need the `TemplateExecutor` type, which currently isn't exported by `@types/lodash-es` (though fixable). I also enjoy using `lodash-webpack-plugin`.

And why close this issue? Isn't this a bug? Same as #180, which isn't really an enhancement, but actually a bug too.

**Comment by jdalton** [comment]
Seems more like an enhancement. I'll designate this a dup of #180.
