### ISSUE TITLE
lodash v4 has removed category directories

### ISSUE THREAD

**Issue by jdalton** [lodash/babel-plugin-lodash#22]
For example `require('lodash/collection/partition')` is now `require('lodash/partition')`

**Comment by gajus** [comment]
Implemented in [`babel-plugin-lodash-modularize`](https://github.com/gajus/babel-plugin-lodash-modularize/issues/3)@0.3.0.

**Comment by megawac** [comment]
@jdalton should paths be resolved as `import <method> from 'lodash/<method>'`. This would make things much easier (i.e. no sync fs IO stuff)

**Comment by jdalton** [comment]
Yes, except for the `internal` folder.

**Comment by megawac** [comment]
true that

**Comment by megawac** [comment]
we'll reevaluate our module detection strategy going forward

**Comment by jdalton** [comment]
We could `glob` it up.
