### ISSUE TITLE
publish 3.3.3 to npm

### ISSUE THREAD

**Issue by octaharon** [lodash/babel-plugin-lodash#220]
Hey man, that's a great package, too bad I can't use it, as previous (3.3.2) version brings in Babel 6 still. Would you consider publishing the Babel 7 version to npm, it's been 7 months already :)

**Comment by jdalton** [comment]
Published https://github.com/lodash/babel-plugin-lodash/commit/88f4943193f26190abc2c6379ebe927ab4735360 :tada:
