### ISSUE TITLE
Doesn't seem to be working with babel@7.x

### ISSUE THREAD

**Issue by niftylettuce** [lodash/babel-plugin-lodash#221]
Here's my `.babelrc`:

```json
{
  "presets": [
    ["@babel/env", {
      "targets": {
        "node": "6.4.0"
      }
    }]
  ],
  "plugins": [ "lodash" ],
  "sourceMaps": "inline"
}
```

Here's an example file:

```js
const _ = require('lodash');

const foo = _.isString('hello world');
console.log('foo', foo);
```

I'd expect it to be like this after running through with babel, but it's not:

```
const isString = require('lodash/isString');

const foo = isString('hello world');
console.log('foo', foo);
```

Any idea why?  I'm on babel 7x. and all my packages use `@babel/xyz` org.

**Comment by jdalton** [comment]
Hi @niftylettuce!

This plugin transforms ES6 import syntax. See [the usage example](https://github.com/lodash/babel-plugin-lodash#example).

**Comment by niftylettuce** [comment]
Ah, thanks @jdalton didn't know it was specific for ES.  I'm not sure if you know of an alternative for `require` other than just doing it manual?

**Comment by jdalton** [comment]
There may be a transform out there on npmjs.com.

**Comment by niftylettuce** [comment]
I wasn't able to find one - is it not easy to add support for it in this package?

**Comment by jdalton** [comment]
I had better luck: [lebab](https://www.npmjs.com/package/lebab), [replace-require-with-import](https://www.npmjs.com/package/replace-require-with-import), [require-to-import](https://www.npmjs.com/package/require-to-import),

**Comment by jdalton** [comment]
I've used `lebab` before :D

**Comment by niftylettuce** [comment]
I was trying to find something that simply just worked for `require` without having to transform to `import` 😢
