### ISSUE TITLE
Explain in README  what's options.id for

### ISSUE THREAD

**Issue by yairEO** [lodash/babel-plugin-lodash#223]
I don't understand the README...

### First you give the example:

    "plugins": ["lodash"]

### Then

    "plugins": [["lodash", { "id": "lodash-compat", "cwd": "some/path" }]]

Without explaining what is the purpose of this mysterious code and why/when would I need to give `id`

**Comment by jdalton** [comment]
Hi @yairEO!

The `id` can be used to make `babel-plugin-lodash` work with other lodash-like packages. In the example it is using `lodash-compat`.

**Comment by yairEO** [comment]
Hi, thanks for replying so quickly.

I am unable to import lodash template..
https://github.com/rollup/rollup/issues/691

**Comment by jdalton** [comment]
Try
```js
import { template } from 'lodash-es'
```
