### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by mbfisher** [lodash/babel-plugin-lodash#225]
Hi! It looks like the work has been done to support Babel 7 - do you know when you'll release it?

**Comment by jdalton** [comment]
The plugin should already be compatible with Babel 7. The commit in master is for using Babel 7 for tests.

**Comment by jonjamz** [comment]
When I install this I'm getting `@3.3.4` but the dependencies are for babel `^7.0.0-beta.49` which is causing an error about version mismatch in .babelrc. Looks like there is a discrepancy between the package.json in this repo and the one published on NPM.

Edit: Ok I see the version tagged `3.3.4` indeed has the beta dependency whereas the current master is listed as `3.3.4` but has `7.0.0`.
