### ISSUE TITLE
Example ?

### ISSUE THREAD

**Issue by Calvein** [lodash/babel-plugin-lodash#25]
I've tried to add it to a current project but it failed with this kind of error:

> Error: index.js: lodash method map was not in known modules
    Please file a bug if it's my fault https://github.com/megawac/babel-plugin-lodash/issues

So I made [a very tiny example] and I have the same problem, where `babel index.js > babel.js` is fine but `babel --plugins lodash index.js > babel-lodash.js` triggers the same error (even if added in `.babelrc`)

Here's [my example], what am I doing wrong ?

Thanks.

[a very tiny example]: https://github.com/lodash/babel-plugin-lodash/blob/master/test/fixtures/multi-specifier/actual.js
[my example]: https://cdn.fbsbx.com/hphotos-xal1/v/t59.2708-21/12408595_10153813447253774_1525338575_n.gz/lodash-test.tar.gz?oh=2e75a1af8263ea48b6258673d7100f95&oe=569972D6&dl=1

**Comment by megawac** [comment]
Hey, this plugin hasbt been updated for lodash v4 yet. Ill be updating it tonight

**Comment by megawac** [comment]
See #22

**Comment by Calvein** [comment]
No worries, lodash 4 changelog got me too excited.

**Comment by megawac** [comment]
Fixed in [v2.0.1](https://github.com/lodash/babel-plugin-lodash/tree/v2.0.1)
