### ISSUE TITLE
_.join missing in known modules

### ISSUE THREAD

**Issue by nicolam1** [lodash/babel-plugin-lodash#26]
Hey,
I got this error when using _.join:

Error: ../entities-utils.js: lodash method join was not in known modules
Please file a bug if it's my fault https://github.com/megawac/babel-plugin-lodash/issues

Letting you know.

**Comment by jdalton** [comment]
@nicolam1 Make sure you're using Lodash v4. The `_.join` method was exposed in v4.

**Comment by nicolam1** [comment]
Thank you
