### ISSUE TITLE
reading the `_` value, rather than a function on it, becomes invalid after transform

### ISSUE THREAD

**Issue by seansfkelley** [lodash/babel-plugin-lodash#27]
I discovered this when I wrote some test code that slaps `_` onto `window` so I can play around with it during development. I don't know if there's a real use case for it, but I figured I'd bring it to your attention anyway. Check out https://github.com/seansfkelley/babel-plugin-lodash-bug for a failing example of what I mean.

**Comment by megawac** [comment]
That's a case outside of the scope of this function. You can use https://github.com/megawac/lodash-modularize (which still needs to be updated to support v4) if you wish. Otherwise you can do something like

```
import {filter, map} from 'lodash'

window._ = {filter, map};
```

If anything the plugin could throw errors for this case
