### ISSUE TITLE
ReferenceErrors due to bad transpilation

### ISSUE THREAD

**Issue by a-s-o** [lodash/babel-plugin-lodash#28]
Hello,

Thanks for the plugin, it is very convenient. I would just like to report an error I am running into:

I have the following code:
```javascript
import {
  clone,
  get,
  set,
  has,
  mapValues,

  isPlainObject as isObj,
  isFunction as isFn,

  constant,
  noop,
  identity,
} from 'lodash';
```

and it is transpiling into this:
```javascript
	var _has = __webpack_require__(290);
	
	var _has2 = _interopRequireDefault(_has);
	
	var _isPlainObject = __webpack_require__(322);
	
	var _isPlainObject2 = _interopRequireDefault(_isPlainObject);
	
	var _mapValues = __webpack_require__(291);
	
	var _mapValues2 = _interopRequireDefault(_mapValues);
	
	var _clone = __webpack_require__(294);
	
	var _clone2 = _interopRequireDefault(_clone);
	
	var _set = __webpack_require__(317);
	
	var _set2 = _interopRequireDefault(_set);
	
	var _get = __webpack_require__(104);
	
	var _get2 = _interopRequireDefault(_get);
	
	var _constant = __webpack_require__(319);
	
	var _constant2 = _interopRequireDefault(_constant);
	
	var _isFunction = __webpack_require__(44);
	
	var _isFunction2 = _interopRequireDefault(_isFunction);
```

Specifically, `noop` and `identity` are missing which leads to `ReferenceError: noop is not defined`. I cannot figure out why they might be getting excluded. I am running the latest version of the plugin.
```
> ~/code> npm show babel-plugin-lodash version
> 2.0.1
```

Any help is much appreciated. Thanks

**Comment by a-s-o** [comment]
I will also add that just doing `import _ from 'lodash';` works just fine and is the workaround I am using for now as those modules are being required separately as they should with this plugin. 

The issue is only when explicitly declaring imported functions.

**Comment by jdalton** [comment]
I noticed you had a rogue trailing comma in your imports after `identity`.
If you remove that does it work?

**Comment by a-s-o** [comment]
Hi, thanks for looking into this. Unfortunately it is the same behaviour even without the trailing comma; stops at `noop` again. I also tried putting everything on one line:

```javascript
import { clone, get, set, has, mapValues, reduce, defaults, isPlainObject, isFunction, constant, noop, identity } from 'lodash';
```
Here is my babel config:
```
      {
          presets: [ 'es2015', 'react' ],
          plugins: [ 'lodash' ]
        }
```
The output stops at `isFunction` in all scenarios.

**Comment by a-s-o** [comment]
Just to try some more variations, I also tried the following where, I am using all other functions from `_` variable but ask for noop and identity to be destructured:
```
import _ from 'lodash';
import { noop, identity } from 'lodash'; 
```
I get the same result as before; the plugin works by replace all _ references, for instance `_.isFunction` references with separate requires but again skips `noop` and `identity` which transpile to nothing. Very weird.

**Comment by jdalton** [comment]
Can you repro @megawac?

**Comment by megawac** [comment]
I cannot reproduce, make sure you're using the methods in your code?

**Comment by a-s-o** [comment]
Okay, thanks for trying. I am happy with the workaround for now and in almost all other cases the destructuring works fine. Just seems to be a freak issue (babel issue or my setup perhaps). If I run into it again, I will try to isolate and make a reproducible demo. 

Thanks again for taking the time and looking. Closing for now.

**Comment by megawac** [comment]
How are you using the functions @a-s-o? it may have something to do with how they're being used.

For instance (the plugin supports this) you may be doing

```
map(arr, identity)
``

**Comment by a-s-o** [comment]
I am have a function which accepts an object which may optionally includes with two methods `initialize` and `validate`. If these are not provided I use noop and identity as the defaults. Excerpt:
```javascript
import { noop, identity } from 'lodash';

export function createModel (src = {}) {
   const initialize = src.initialize || noop;
   const validate = src.validate || identity;

   // do some other things

  // Return a new object with some defaults applied, etc.
  return { initialize, validate, /* ... other properties */ };
}

```
So, I am not really using the lodash functions right away but they may get invoked down the line.

**Comment by megawac** [comment]
Ah, that isn't supported at the moment.

**Comment by smashercosmo** [comment]
Would it be backported to 0.2 branch?

**Comment by megawac** [comment]
Going to wait for https://phabricator.babeljs.io/T7078 to resolve before publishing

**Comment by jdalton** [comment]
Can the `issues` branch be deleted?

**Comment by jdalton** [comment]
@megawac It looks like https://phabricator.babeljs.io/T7078 is waiting on a repro from you.

**Comment by megawac** [comment]
Published in v2.1

On Mon, Feb 22, 2016 at 3:02 PM, John-David Dalton <notifications@github.com

**Comment by jdalton** [comment]
Cool! Can you close out the babel bug too.

**Comment by megawac** [comment]
Not sure how lol

On Mon, Feb 22, 2016 at 3:23 PM, John-David Dalton <notifications@github.com

**Comment by jdalton** [comment]
You have to edit the original message and change its state to close from open. It takes some getting used to.

**Comment by smashercosmo** [comment]
So, am I right, there will be no backporting to 0.2 branch?

**Comment by megawac** [comment]
Sure @smashercosmo, created a branch and a 0.3 release with that commit. Probably not going to do much maintenance on that branch though. Feel free to direct PRs against it

**Comment by smashercosmo** [comment]
@megawac that was fast) awesome, thx a lot
