### ISSUE TITLE
Spread operator

### ISSUE THREAD

**Issue by molily** [lodash/babel-plugin-lodash#29]
Thanks for this great project!

I’m running into an issue with this simple code:

```javascript
import _ from 'lodash';

const mergeOptions = (...args) =>
  _.merge({}, ...args);

console.log(
  _.merge({ a: 1 }, { b: 2 }) // Yep
);

console.log(
  mergeOptions({ c: 3 }, { d: 4 }) // Nope
);
```

The first normal call to `_.merge` works fine, but the second with the spread isn’t recognized: `Uncaught ReferenceError: _ is not defined`

Looking at the Babel output, this is logical since the spread compiles to a `merge.apply(_, Array)` call.

```javascript
var _merge = __webpack_require__(96);
var _merge2 = _interopRequireDefault(_merge);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
var mergeOptions = function mergeOptions() {
  for (var _len = arguments.length, args = Array(_len), _key = 0; _key < _len; _key++) {
    args[_key] = arguments[_key];
  }
  return _merge2.default.apply(_, [{}].concat(args)); // 🔥💥💢
};
console.log((0, _merge2.default)({ a: 1 }, { b: 2 }));
console.log(mergeOptions({ c: 3 }, { d: 4 }));
```

That’s technically correct since the original call was `_.merge` and Babel wants to preserve the `this` binding…

Is there anything you can do here to solve this? For the purpose of Lodash, would it be possible to change this to `.apply(undefined, Array)` since the binding doesn’t matter for Lodash AFAIK?

Thanks for your time! :)

**Comment by megawac** [comment]
Interesting, the fastest fix for you would probably be to just

```js
import _, {merge} from 'lodash';

const mergeOptions = (...args) =>
  merge({}, ...args);
```

Not exactly sure how I want to handle this yet

**Comment by megawac** [comment]
Its weird that the presets, transpiling the spread to ES5 is running before this plugin. I would expect babel to see

```js
import _merge from 'lodash/merge';

const mergeOptions = (...args) =>
  _merge({}, ...args);
```

I think babel might of changed this behaviour in a recent version (6.5). What version are you using out of curiousity

**Comment by yvele** [comment]
Same problem for me and I'm using **babel-cli 6.5.1** with **babel-plugin-lodash 2.0.1**

```es6
import lodash from "lodash";
let a = lodash.merge({}, ...args);
```

is transpilled to

```js
var _merge = require("lodash/merge");
var _merge2 = _interopRequireDefault(_merge);
var a = _merge2.default.apply(lodash, [{}].concat(args));
```

**Comment by megawac** [comment]
Having issues with this one. Although I can definitely reproduce it ([in unit tests](https://github.com/lodash/babel-plugin-lodash/tree/master/test/skipped-fixtures/spread-operator)) I have failed to isolate it in an example [repo for the issue](https://github.com/megawac/babel-spread-issue).

**Comment by jdalton** [comment]
Pinging @hzoo for assistance.

When running the [spread test file](https://github.com/lodash/babel-plugin-lodash/blob/master/test/skipped-fixtures/lodash-spread-operator/actual.js) of the [plugin](https://github.com/lodash/babel-plugin-lodash/blob/3a4fae6ed3d592f9be4d936a1c41a31463d57a5d/src/index.js#L68):
```bash
npm run build && babel --plugins ./lib/index.js ./test/skipped-fixtures/lodash-spread-operator/actual.js
```

It produces code like
```js
_merge6.default.apply(_, [{}].concat(_toConsumableArray(args)));
_merge4.default.apply(fp, [{}].concat(_toConsumableArray(args)));
```
Where I'd like the `_` and the `fp` to be `undefined` as [in here](https://github.com/lodash/babel-plugin-lodash/blob/master/test/skipped-fixtures/lodash-spread-operator/expected.js).
I've tried to dig into the [spread plugin](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-es2015-spread/src/index.js) but I think it's executing before our source transform and so setting a context of `_` or `fp` before we can remove the member expression.

Do you have any pointers?

**Comment by jdalton** [comment]
Any pointers @thejameskyle?

**Comment by hzoo** [comment]
Glad to see you figured it out (probably before I could too 😄 )

**Comment by jdalton** [comment]
Ended up drying it out more too https://github.com/lodash/babel-plugin-lodash/blob/6d8be9bde3dcf1d07a8ddbf3dbe506dcac64b973/src/index.js#L159-L161.

**Comment by jdalton** [comment]
@loganfsmyth
Could you sanity check this:
```js
npm run build && babel --plugins ./lib/index.js ./test/fixtures/lodash-spread-operator/actual.js
```
now errors for me with smth like:
```js
ReferenceError: Unknown plugin "./lib/index.js" specified in "base" at 0, attempted to resolve relative to "./test/fixtures/lodash-spread-operator"
    at /Users/jdalton/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:179:17
```
