### ISSUE TITLE
Add fromPairs support

### ISSUE THREAD

**Issue by mjrussell** [lodash/babel-plugin-lodash#30]
`lodash method fromPairs was not in known modules`

https://lodash.com/docs#fromPairs

**Comment by jdalton** [comment]
Are you using lodash v4?

**Comment by mjrussell** [comment]
Ugh I had a bad lodash node_modules directory, blowing it away and reinstalling v4 fixed the issue

**Comment by jdalton** [comment]
Thanks for the update!
