### ISSUE TITLE
Update fp conversion

### ISSUE THREAD

**Issue by jdalton** [lodash/babel-plugin-lodash#31]
The readme currently has

>
## Example
>
Transforms
>
```js
import lodash from 'lodash';
import { add } from 'lodash/fp';
>
let add1 = add(1);
lodash.map([1, 2, 3], add1);
```
>
roughly to
>
```js
import _add from 'lodash/math/add';
import _map from 'lodash/collection/map';
import convert from 'lodash/fp/convert';
>
const _fp = convert({
  'add': _add
});
>
let add1 = _fp.add(1);
_map([1, 2, 3], add1);
```

but with 4.1.0 individual fp modules exist so they could be used instead.

**Comment by megawac** [comment]
@jdalton any reason to change it? That seems like it would just increase the number of files imported (though it could possibly solve a babel 6.5 bug for the repo)

**Comment by jdalton** [comment]
> any reason to change it

Does "because it looks prettier" count? Because that was my thinking :grinning:

**Comment by jdalton** [comment]
```js
import _add from 'lodash/fp/add';
import _map from 'lodash/map';
>
let add1 = _add(1);
_map([1, 2, 3], add1);
```

**Comment by megawac** [comment]
It's transpiled code, less bytes is better is my thinking

**Comment by jdalton** [comment]
Ok.

**Comment by megawac** [comment]
The other argument I'd have against it is that it requires lodash>=4.1? removing support for plugin support for 4.0

**Comment by jdalton** [comment]
> The other argument I'd have against it is that it requires lodash>=4.1? removing support for plugin support for 4.0

I'd be cool with that. 4.0 was super buggy.
