### ISSUE TITLE
Support partial/wrapperMethod placeholders

### ISSUE THREAD

**Issue by megawac** [lodash/babel-plugin-lodash#33]
```js
_.partial(function() {

}, _, _, 1);
```

Will exhibit the same issues as #29. Thoughts on how to transpile @jdalton?

**Comment by jdalton** [comment]
Each method with placeholder support has it anchored to its module so:
```js
var partial = require('lodash/partial'),
     ph = partial.placeholder;

partial(function() { }, ph, ph, 1);
```

**Comment by jdalton** [comment]
They aren't ness the same reference though so they should be paired. By that I mean `partial.placeholder` may not `===` the `curry.placeholder`
