### ISSUE TITLE
"npm install babel-plugin-lodash@latest" results in installing v0.3.0

### ISSUE THREAD

**Issue by boneskull** [lodash/babel-plugin-lodash#35]
This is either an npm v3 issue or a babel-plugin-lodash issue.

```shell
$ npm install babel-plugin-lodash@latest -D
<...snip...>
├─┬ babel-plugin-lodash@0.3.0
│ └── lodash@3.10.1
<...snip...>
```

If the tags are being published correctly, this is an npm bug.

**Comment by jdalton** [comment]
Fixed. When v0.3.0 was published it wasn't tagged so it defaulted to `latest`. I've corrected it.
