### ISSUE TITLE
cannot import {noop} from 'lodash'

### ISSUE THREAD

**Issue by boneskull** [lodash/babel-plugin-lodash#36]
(assuming this is a `babel-plugin-lodash` issue)

```js
import {noop} from 'lodash'
```

results in `noop` having a value of `undefined`.

```js
import noop from 'lodash/noop';
```

results in `noop` having a value of the `noop` function.

I have not tested this against `lodash/fp/noop` or `{noop} from lodash/fp`.

lodash@4.5.1, babel-plugin-lodash@2.1.0

**Comment by danez** [comment]
I have the same problem:

```js
import { kebabCase, camelCase } from 'lodash';

export const nameFormatters = {
  scss: kebabCase,
  json: camelCase,
};
```
results in:
```
'use strict';

exports.__esModule = true;
var nameFormatters = exports.nameFormatters = {
  scss: kebabCase,
  json: camelCase
};
```
