### ISSUE TITLE
Named import from lodash/fp fails when used as a function argument

### ISSUE THREAD

**Issue by lukethenuke** [lodash/babel-plugin-lodash#40]
I have managed to repro it down to the following:
using lodash (v4.6.1) and babel-plugin-lodash (v2.2.1)
the code was run with babel-cli (v6.6.5) on windows 7

```
import { filter, isObject } from 'lodash/fp'
filter(isObject)
// ->
// import _isObject from 'lodash\\fp\\isObject';
// import _filter from 'lodash\\fp\\filter';

// _filter(isObject); // <- notice the missing _ from isObject
```
Some notes:
The filter function does not need to come from lodash, anything will do in its place. 
The isObject function can be anything from lodash/fp
Importing from 'lodash' works
Importing the default export directly works (eg. import isObject from 'lodash/fp/isObject')
```
import { map, isArray } from 'lodash/fp'
const f = 1//dummy function
f(map)
isArray

import { filter, isObject } from 'lodash'
filter(isObject)

import { maxBy } from 'lodash/fp'
import sum from 'lodash/fp/sum'
maxBy(sum)
// ->
// import _isArray from 'lodash\\fp\\isArray';
// import _map from 'lodash\\fp\\map';
// const f = 1; //dummy function
// f(map);
// isArray;

// _filter(_isObject);

// import sum from 'lodash/fp/sum';
// _maxBy(sum);
```
Workaround:
Importing the default export:
```
import isObject from 'lodash/fp/isObject'
```

**Comment by 0x80** [comment]
I ran into the same problem. The workaround to import from /fp directly defeats the use of this plugin no?

**Comment by jdalton** [comment]
Moving to #43.

**Comment by jdalton** [comment]
Reopening after reverting previous patch.

**Comment by jdalton** [comment]
Closed via https://github.com/lodash/babel-plugin-lodash/commit/4b1ea1b784ddf98f1b07efd6425559593a9d1677.
