### ISSUE TITLE
Example to make this work with webpack / babel-loader

### ISSUE THREAD

**Issue by gebrits** [lodash/babel-plugin-lodash#41]
babel-plugin-lodash looks awesome. However, I can't get it to load in my webpack/ babel-loader pipeline. 
Has anyone managed to get it to work in combination with webpack?

**Comment by viveleroi** [comment]
I have, without any issue. I added this plugin to the `.babelrc` config file, included lodash in my source, and presto. https://github.com/helion3/inspire-tree/tree/bundle

**Comment by brandondoran** [comment]
I too get an error in my webpack build after adding `"lodash"` to `.babelrc`. I have not figured it out yet.
```
webpack --config webpack.config.js --progress --profile --colors

/Users/brandon/projects/XXXXXX/babel-core/lib/transformation/file/options/option-manager.js:243
      this.log.error("Invalid options type for " + alias, TypeError);
```

**Comment by brandondoran** [comment]
My problem was I added "lodash" to `presets` instead of `plugins` in `.babelrc`. Works like a charm once I corrected that.

**Comment by jjt** [comment]
I'm facing the same issue here, and I'm wondering if it has to do with [babel-plugin-resolver](https://github.com/jshanson7/babel-plugin-resolver), which I'm using.

At [index.js#L59](https://github.com/lodash/babel-plugin-lodash/blob/master/src/index.js#L59), this check in `ImportDeclaration` always fails because it's getting the absolute path:

```js
if (value.indexOf('lodash') !== -1) console.log(value);
// -> /Users/jjt/path/to/project/node_modules/lodash

// L59: This conditional always fails because it's an absolute path
if (fp || value == 'lodash') {
  // ...
}
```

**Comment by megawac** [comment]
@jjt interesting, would #15 work if we added support for something like

`[require('babel-plugin-transform-es2015-template-literals'), { 'lodash-path': 'node_modules/lodash'}]`

Though because your path there is absolute it would not be possible to transfer that logic between computers

**Comment by megawac** [comment]
Also if someone is interested in making a webpack example it'd be greatly appreciated

**Comment by jdalton** [comment]
I've gotten the babel plugin to work in a test webpack setup. I'll add a doc example soon.

**Comment by jdalton** [comment]
It's basically:
```js
  'module': {
    'loaders': [{
      'loader': 'babel',
      'test': /\.js$/,
      'exclude': /node_modules/,
      'query': {
        'plugins': ['lodash'],
        'presets': ['es2015'],
      }
    }]
  }
```

**Comment by jdalton** [comment]
In next release of babel-plugin-lodash will also allow you to pass the lodash package id so that it won't have to guess.
```js
'query': {
  'plugins': [['lodash', { 'id': 'lodash-compat' }],
  'presets': ['es2015'],
}
```

**Comment by megawac** [comment]
Nice that was originally how I was going to solve https://github.com/lodash/babel-plugin-lodash/issues/15

**Comment by jdalton** [comment]
> Nice that was originally how I was going to solve #15

This is also how we're able to test `lodash`, `lodash-es`, and `lodash-compat` at once too.

**Comment by jdalton** [comment]
Patched with https://github.com/lodash/babel-plugin-lodash/commit/a79e24a56d4f10ffdbcf2b7d9196f6fdc3dd2437 and https://github.com/lodash/babel-plugin-lodash/commit/486bda88396f1603c7b079ac22a8dff6bee45b04 and
