### ISSUE TITLE
Better tree shaking

### ISSUE THREAD

**Issue by viveleroi** [lodash/babel-plugin-lodash#42]
I'm converting a project which imports individual lodash modules (`import each from 'lodash.foreach'`) to use this plugin instead (this plugin helps me avoid a webpack amd/define bug).

However, there's still a lot of lodash code left in place that my code isn't using - in my case the difference is 143k (uncompressed) more code compared to when I loaded the files individually.

Looking at the diff, I see a bunch of variables and other methods unrelated to anything I use.

**Comment by jdalton** [comment]
The plugin rewires module requires. Tree shaking is the side effect.
