### ISSUE TITLE
how to use lodash mixins?

### ISSUE THREAD

**Issue by gex** [lodash/babel-plugin-lodash#44]
hi,

i'm migrating an old project to es6 and babel and this is an extremely useful plugin for me but i don't know how to use [mixins](https://lodash.com/docs#mixin) to prevent this error:
```
Module build failed: Error: /app/.../myFile.js: lodash method myFunction was not in known modules.
```

i try to use
```js
import _ from 'lodash'

_.mixin({
  myFunction(o) {
    // ...
  }
})
```

is this even possible? :)

**Comment by megawac** [comment]
I don't think there is a good way for this plugin to support mixins, especially mixins originating in other files. The simplest approach would be to simply convert a mixin to a function, but again, it runs into the issue of mixins in other files.

I think I'd suggest just not using `mixin` as it has minimal benefits outside of chaining which is also not supported by this plugin. Further it would be extremely difficult + not worth it to resolve where the mixin originated if it was from another file.

**Comment by megawac** [comment]
(I also am not ready to throw a warning as mixin can be used with different source objects, though I suppose args could be inspected)

**Comment by gex** [comment]
thank you @megawac for the answer!
