### ISSUE TITLE
SyntaxError: Unexpected token default

### ISSUE THREAD

**Issue by not-an-aardvark** [lodash/babel-plugin-lodash#53]
I have a module file that causes a syntax error when transformed with babel-plugin-lodash.

The module file:

```js
// myModule.js

export {default as theCryptoModule} from 'crypto';

```

The `.babelrc`file:

```json
{
  "plugins": [
    "lodash",
    "transform-es2015-modules-commonjs"
  ]
}
```

I transpiled it using:

```
node_modules/.bin/babel myModule.js --out-file transpiledModule.js
```

The output file `transpiledModule.js` looks like this:

```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.theCryptoModule = default;
```

Running this file with `node transpiledModule.js` gives the following error:

```
/path/to/transpiledModule.js:6
exports.theCryptoModule = default;
                          ^^^^^^^
SyntaxError: Unexpected token default
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

Note that this issue no longer occurs if babel-plugin-lodash is removed from the `.babelrc` file.

---

I'm using Node v6.0.0, `babel-cli@6.8.0`, `babel-plugin-lodash@3.0.0`, and `babel-plugin-transform-es2015-modules-commonjs@6.8.0`, all freshly installed from the npm registry:

```bash
$ rm -rf node_modules/
$ npm install babel-cli babel-plugin-transform-es2015-modules-commonjs babel-plugin-lodash
```

It's possible that this is an upstream issue, since I think it was working before `babel@6.8.0` got released yesterday. However, I don't know enough about the internals of babel or babel-plugin-lodash to be sure of where the issue is coming from.

**Comment by jdalton** [comment]
I can't repro this. If you don't have `lodash` installed then it should error with
```bash
Error: Cannot find module 'lodash'
```
with `lodash` installed the output I get is:
```js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _crypto = require('crypto');

Object.defineProperty(exports, 'theCryptoModule', {
  enumerable: true,
  get: function () {
    return _interopRequireDefault(_crypto).default;
  }
});

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

**Comment by not-an-aardvark** [comment]
Thanks for looking into it, but that's confusing because it's definitely occurring for me (for one reason or another).

I made [a repo](/not-an-aardvark/babel-plugin-lodash-bug-demo) to demonstrate it -- are you able to reproduce it with that?

**Comment by jdalton** [comment]
It's something with your npm-shrinkwrap. If I delete that then I get a different error related to not having lodash installed. It's not the proper error so a bug on the plugin but not related to the transform.

**Comment by not-an-aardvark** [comment]
It looks like there's a preinstall script that's getting run from somewhere, which might be causing the issue:

```
> fsevents@1.0.12 install /path/to/babel-plugin-lodash-bug-demo/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /path/to/babel-plugin-lodash-bug-demo/node_modules/fsevents/lib/binding/Release/node-v48-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
```

I was able to toggle the bug by doing this:

```
$ rm npm-shrinkwrap.json
$ rm -rf node_modules/
$
$ npm config set ignore-scripts true
$ npm install && npm test # no error
$ rm -rf node_modules/
$
$ npm config set ignore-scripts false
$ npm install && npm test # error!
```

**Comment by not-an-aardvark** [comment]
I'm trying to find where this issue is coming from, but I can't seem to figure out why you're not able to reproduce it. The shrinkwrap file in the repo was generated by simply running `npm install` followed by `npm shrinkwrap`.

I tried running the demo on a travis server, and a SyntaxError appeared regardless of whether a shrinkwrap was present. ([Here's](https://travis-ci.org/not-an-aardvark/babel-plugin-lodash-bug-demo/builds/127849160) the build with the shrinkwrap, and [here's](https://travis-ci.org/not-an-aardvark/babel-plugin-lodash-bug-demo/builds/127849297) the build without a shrinkwrap -- both of them confirm this bug.)

**Comment by jdalton** [comment]
Patched! Thanks for digging in!

**Comment by not-an-aardvark** [comment]
Thanks!
