### ISSUE TITLE
Use webpack context for resolving lodash module paths

### ISSUE THREAD

**Issue by dlindenkreuz** [lodash/babel-plugin-lodash#56]
At the moment, the plugin uses `process.cwd()` for finding a local lodash installation ([config.js, line 31](https://github.com/lodash/babel-plugin-lodash/blob/master/src/config.js#L31)).

When running a devserver in a different directory than the root of the files to be compiled, lodash modules cannot be resolved and webpack quits building early.

**Example**:

- express with webpack-dev-middleware runs in `./index.js`, directory is also cwd
- webpack config is in `./frontend/`
- frontend code is in `./frontend/`
- lodash is a dependency in `./frontend/package.json`
- `.babelrc` is in `./frontend`

Lots of errors like this one ensue:
```
ERROR in ./frontend/src/components/x.js
Module not found: Error: Cannot resolve module 'lodash/string/capitalize' in /Users/daniel/x/frontend/src/components
 @ ./frontend/src/components/x.js 31:19-54
```

**Current workaround**: install lodash as a dependency in the cwd

**Suggestion**: Use the `context` property from the webpack config as root for resolving lodash.

**Comment by jdalton** [comment]
If you're up for creating a PR that would rock.

**Comment by megawac** [comment]
Probably what makes most sense is to take the `cwd` as a plugin option

**Comment by dlindenkreuz** [comment]
That was quick, thanks!
