### ISSUE TITLE
babel-plugin-lodash and babel-plugin-transform-object-rest-spread can cause an error when used together

### ISSUE THREAD

**Issue by not-an-aardvark** [lodash/babel-plugin-lodash#60]
For reference, [babel-plugin-transform-object-rest-spread](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread) is an official plugin that transpiles [this stage 2 proposal](/sebmarkbage/ecmascript-rest-spread).

---

Test file:

```js
// test.js

import {keys} from 'lodash';

var {a: theFirstProperty, ...theOtherProperties} = {a: 1, b: 2, c: 3};

console.log(keys({a: 1, b: 2, c: 3}));

// expected: ['a', 'b', 'c']

```

.babelrc:

```json
{
  "plugins": [
    "lodash",
    "transform-es2015-modules-commonjs",
    "transform-es2015-destructuring",
    "transform-object-rest-spread"
  ]
}
```

Transpiled using:

```
babel --out-file transpiledTest.js test.js
```

The transpiled file looks like this:

```js
// transpiledTest.js

'use strict';

var _keys2 = require('lodash/keys');

var _keys3 = _interopRequireDefault(_keys2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (_keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }

var _a$b$c = { a: 1, b: 2, c: 3 };
var theFirstProperty = _a$b$c.a;

var theOtherProperties = _objectWithoutProperties(_a$b$c, ['a']);

console.log((0, _keys3.default)({ a: 1, b: 2, c: 3 }));

// expected: ['a', 'b', 'c']
```

Running the transpiled file with `node transpiledTest.js` (using Node 6.1.0) gives the following error:

```
/path/to/transpiledTest.js:9
function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (_keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }
                                                                                         ^

ReferenceError: _keys is not defined
    at _objectWithoutProperties (/path/to/transpiledTest.js:9:90)
    at Object.<anonymous> (/path/to/transpiledTest.js:14:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:445:3
```

The bug only occurs when importing `lodash.keys`.

It seems to happen because the `_objectWithoutProperties` function created by babel usually looks vaguely like this:

```js
function (obj, keys) { doSomethingWith(keys) }
```

...but in this case it ends up looking like this:

```js
// note: the parameter is still called `keys` even though the reference changed to `_keys`
function (obj, keys) { doSomethingWith(_keys) }
```

**Comment by jdalton** [comment]
So the fix I have isn't super. It's just more restrictive. Ideally we'd know that the `keys` referenced in the helper code isn't the `keys` of the module but that would require a bit more inspection and I'd like to keep things simple for now.

**Comment by not-an-aardvark** [comment]
Thanks for the fix.

I remember from messing around with babel plugins in the past that babel's plugin API exposes a [generateUidIdentifier](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#generating-a-uid) function to avoid conflicts with local variables. Would that be applicable here?

**Comment by jdalton** [comment]
The identifiers are already generated with `generateUidIdentifier` by `path.hub.file.addImport`.

**Comment by jdalton** [comment]
The issue isn't generated ids it's the the helpers vars shadow those in an outer scope. So I'd have to inspect and walk scopes (gross).

**Comment by not-an-aardvark** [comment]
Ah alright, that makes sense. Thanks for the clarification.

**Comment by jdalton** [comment]
Turns out a more robust check was easy after all. https://github.com/lodash/babel-plugin-lodash/commit/4a9f9460eeda0f23feb713ee77ae09e10d8634cf

**Comment by jdalton** [comment]
Moved the checks into helper functions and applied them to all other areas. https://github.com/lodash/babel-plugin-lodash/commit/faea5c72eeb19e5e34497bb4cd3325c42a48d035.
