### ISSUE TITLE
_.each transforms into arrayEach?

### ISSUE THREAD

**Issue by elado** [lodash/babel-plugin-lodash#73]
I use `_.each` for objects too, but seems like it's turning it into an `arrayEach`, which doesn't let me iterate through arrays.

Bug?

<img width="497" alt="screen shot 2016-05-26 at 5 35 01 pm" src="https://cloud.githubusercontent.com/assets/51488/15594181/468100c4-2368-11e6-8845-59477400be41.png">

**Comment by jdalton** [comment]
Sounds like you're using `lodash-webpack-plugin` without the `collections` option enabled.

**Comment by elado** [comment]
Thanks! That explains why the tests didn't fail (no webpack) but it did on the browser (webpack).
