### ISSUE TITLE
Mention "bad practise" approach

### ISSUE THREAD

**Issue by markelog** [lodash/babel-plugin-lodash#75]
Do i understand this correctly - such plugin should be used only if consumer doesn't use tools like rollup or webpack 2 where tree-shaking algorithm is implemented? If so, should this note be added to the docs?

Also, would you agree that this code - 
```js
import _ from 'lodash';

_.map([1, 2, 3], addOne);
```

Is worse then 

```js
import { map } from 'lodash';

map([1, 2, 3], addOne);
```
?

**Comment by markelog** [comment]
> Is worse then

By that i mean "importing" the whole library (at least it is perceived that way) instead of one desired method, complicates understanding what methods is used from library and possible update to new tools in which this plugin wouldn't need to be used.

All and all such code doesn't look obvious to me

**Comment by jdalton** [comment]
This plugin will transform:
```js
import _ from 'lodash';

_.map([1, 2, 3], addOne);
```
as well as code like:
```js
import { map } from 'lodash';

map([1, 2, 3], addOne);
```

Webpack2 and rollup do not support tree-shaking with Lodash.

**Comment by markelog** [comment]
> Webpack2 and rollup do not support tree-shaking with Lodash.

Should this be mentioned in the docs? Do you have a relevant links? 

> as well as code like:

I know, but this is not what i asked

**Comment by jdalton** [comment]
Folks tend to figure it out when they use them. There are open issues on both I believe. Though the gist of the threads are *shrug* since both tree-shaking implementations are too sensitive to potential side-effects, of which Lodash has none.

**Comment by jdalton** [comment]
> I know, but this is not what i asked

Lodash is pretty hands off when it comes to telling folks how to code. It's why we support both styles.

**Comment by markelog** [comment]
I guess you mean https://github.com/webpack/webpack/issues/1750 and https://github.com/rollup/rollup/issues/45? 

I would add those links in readme, like "If you use rollup or webpack 2 this dependency will be no longer needed after following issues will be resolved - ..."

> Lodash is pretty hands off when it comes to telling folks how to code.

I would be interested to hear how would you do this, not as recommendation, but your personal opinion, sorry if this out of the scope a bit

**Comment by jdalton** [comment]
> I would add those links to readme, like "If you use rollup or webpack 2 this dependency will be no longer needed after following issues will be resolved - ..."

I've gotten the impression that those issues won't likely be resolved.
I rather broken tools like webpack 2 and rollup link to us :P
