### ISSUE TITLE
map/alias lodash-compat

### ISSUE THREAD

**Issue by espretto** [lodash/babel-plugin-lodash#78]
it seems the plugin is able to map/alias lodash imports to their compat version through this config snippet taken from the npm readme.
```json
{
  "plugins": [["lodash", { "id": "lodash-compat", "cwd": "some/path" }]],
  "presets": ["es2015"]
}
```
since lodash broke with categories this mechanism seems to be restricted to versions 3.x.x

**Comment by jdalton** [comment]
The `lodash-compat` package is for v3. There isn't a v4 version of `lodash-compat`.
