### ISSUE TITLE
generic version?

### ISSUE THREAD

**Issue by modosc** [lodash/babel-plugin-lodash#85]
first, thanks for this plugin.

i'm curious if you'd be open to having a generic version of this module available ( maybe `babel-plugin-cherry-picker`)?

i made 2 small modifications to the codebase (`defaultIds` in `config.js` and the hard-coded `id == 'lodash'` check in `importModule.js`) and i managed to use it to cherry-pick unused modules from [react-bootstrap](https://react-bootstrap.github.io/). i'm imagining there are other modules that would find this advantageous too. 

for now i plan on forking and creating a separate plugin that's basically identical except my changes but having a centralized place for all the code would be cool and probably really useful.

**Comment by jdalton** [comment]
You can use this now by specifying the "id" option. If you have changes to make it more generic I'm all for it. Send over a PR :)

**Comment by sibelius** [comment]
any progress on this?

any docs of how to make it work with `recharts`, `material-ui` and other packages?

**Comment by jdalton** [comment]
The usage docs show how to specify another package.
