### ISSUE TITLE
Referencing an import value in a void context causes an error.

### ISSUE THREAD

**Issue by mthadley** [lodash/babel-plugin-lodash#86]
I know this is a strange and somewhat contrived use case, but I was wondering if this result is expected:

The following...
```js
import {noop} from 'lodash';

const myNoop = noop;

console.log(noop);

noop;
```

will be transpiled to this:
```js
'use strict';

var _noop2 = require('lodash/noop');

var _noop3 = _interopRequireDefault(_noop2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var myNoop = _noop3.default;

console.log(_noop3.default);

noop;
```
...which will result in the error `ReferenceError: noop is not defined`. I think I would expect the last line to be `_noop3.default;`.

If I don't use `babel-plugin-lodash`, the value is referenced off of the export like `_lodash.noop;` and I don't see an error.

**P.S.** The reason I bring this up is because I'm getting a similar error about `noop` not being defined, and I noticed the above case while trying to debug it. However, my particular use case is hard to distill down to something simple like this, unfortunately.

**Comment by jdalton** [comment]
Thanks!
