### ISSUE TITLE
JSX expressions are not always transformed correctly.

### ISSUE THREAD

**Issue by mthadley** [lodash/babel-plugin-lodash#87]
I noticed that if I am using `babel-plugin-incremental-dom` and `babel-plugin-lodash` together, and I do something like this:

```js
import {noop} from 'lodash';

const myNoop = noop;

console.log(noop);

function render() {
  return <div onClick={noop} />;
}
```

...it will be transpiled to this:
```js
'use strict';

var _noop2 = require('lodash/noop');

var _noop3 = _interopRequireDefault(_noop2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var myNoop = _noop3.default;

console.log(_noop3.default);

function render() {
  return elementVoid('div', null, null, 'onClick', noop);
}
```
which will throw a `ReferenceError` for `noop`.

I think the reason it works with React is because the JSX attributes are passed as an object to `createElement`, and the `Visitor` has a case for `ObjectProperty`. Removing `ObjectProperty` causes transpiled React code to have the same error.

Adding something like this to the `Visitor`:
```js
    'JSXExpressionContainer': replaceNode('expression'),
```
seems to work, but I'm definitely not sure about that being the correct solution.

Thanks!

**Comment by jdalton** [comment]
Ah neat! Can you check that it works if not using JSX (so the verbose ReactDOM API way).

**Comment by jdalton** [comment]
Or the Incremental DOM way.

**Comment by jdalton** [comment]
Also shoutout to @jridgewell!

**Comment by mthadley** [comment]
Yea, both `React.createElement` and `IncrementalDOM.element[whatever]` work. Which makes sense to me since at that point I would expect it to be treated the same as the `console.log()` in the above example (which it apparently does). They are both just function parameters.

**Comment by jridgewell** [comment]
This is probably a bug with `babel-plugin-incremental-dom`. Mind opening over there?

**Comment by jdalton** [comment]
:metal:

I think [JSXExpressionContainer](https://github.com/babel/babylon/blob/cde17b33bd6a42fe73289873e3ef62bad2884481/src/plugins/jsx/index.js#L268) looks ok, there may be more places. A PR would be rad.

**Comment by jdalton** [comment]
I don't think it's a `babel-plugin-incremental-dom` bug. The `babel-plugin-lodash` is just missing the right visitor callback to detect it. It's similar to when we were overlooking `BindExpression`.

**Comment by jridgewell** [comment]
Ohh, I forgot what `babel-plugin-lodash` does. 😬

**Comment by mthadley** [comment]
@jdalton Sure, I can try and send something in a little bit here. 👌

**Comment by jdalton** [comment]
Moved to #88.
