### ISSUE TITLE
Only the last argument of a name in a CallExpression is transformed correctly.

### ISSUE THREAD

**Issue by mthadley** [lodash/babel-plugin-lodash#91]
Starting with this:
```js
import {noop, range} from 'lodash';

function myFunc() {}

myFunc(range, noop);
myFunc(noop, noop);
myFunc(range, noop, noop);
myFunc(range, noop, range, noop);
myFunc(range, noop, range, noop, range);
```
It will be transformed to this:
```js
'use strict';

var _range2 = require('lodash/range');

var _range3 = _interopRequireDefault(_range2);

var _noop2 = require('lodash/noop');

var _noop3 = _interopRequireDefault(_noop2);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function myFunc() {}

myFunc(_range3.default, _noop3.default);
myFunc(_noop, _noop3.default);
myFunc(_range3.default, _noop, _noop3.default);
myFunc(_range, _noop, _range3.default, _noop3.default);
myFunc(_range, _noop, _range, _noop3.default, _range3.default);
```

I'm not sure where the issue is here on this one.

**Comment by jdalton** [comment]
It looks like it's an issue with identifiers repeated as different args.

**Comment by mthadley** [comment]
Also, looks like #90 might solve this?

**Comment by jdalton** [comment]
Ya, I'll hold off digging into this until that one is merged.

**Comment by jridgewell** [comment]
Interesting. It's definitely finding and updating the references (`noop` gets changed to `_noop`), but Babel isn't finding each of them and converting it to the import reference `_noop3.default`. This is directly related to injecting a new import, and probably an upstream issue.

**Comment by jdalton** [comment]
Yep, I saw it finding the references but it seems babel isn't recognizing the changes. \cc @hzoo

**Comment by jdalton** [comment]
Moving to https://github.com/babel/babylon/issues/79.

**Comment by jdalton** [comment]
Circling back. The issue appears to be [Babel cache](https://github.com/babel/babel/pull/3393). We memoize and reuse our identifier objects. However, as this issue shows, it can lead to `path.replaceWith` ignoring repeat identifier replacements. The solution at the moment looks like shallow cloning the `identifier` object to avoid the Babel cache.

**Comment by jridgewell** [comment]
Nice find! `types` provides a `#clone` for nodes, instead of using lodash's.

**Comment by jdalton** [comment]
🙌

**Comment by jdalton** [comment]
I'm not sure all the places that may need the clone but we'll start out with `replaceWith` calls and add as needed.
