### ISSUE TITLE
Convert #chain into a series of calls

### ISSUE THREAD

**Issue by jridgewell** [lodash/babel-plugin-lodash#92]
Post #90, it should be easy to convert from `_.chain().map.filter.take.value` into `_.take(_filter(_.map()))`.

It'll be al little harder to account for shortcut fusion with `_()...`, but it'll probably be doable.

**Comment by megawac** [comment]
What about unfinalized chain sequences which may be passed around? Consider

var c = _.chain([]).map(..)

var f = c.uniqBy(..).value()

**Comment by megawac** [comment]
Im of the opinion that chain isn't worth supporting and we should continue to recommend flow and flowRight/compose patterns

**Comment by jdalton** [comment]
Ya, let's keep it simple-ish for now and continue to punt.

**Comment by lukeapage** [comment]
@jdalton would you accept a pr to do this? We have a very large project and switching to fp now would be too large an effort.

**Comment by jdalton** [comment]
@lukeapage 
> would you accept a pr to do this? We have a very large project and switching to fp now would be too large an effort.

Heck yes!
