### ISSUE TITLE
"Self host" Compile babel-plugin-lodash with babel-plugin-lodash

### ISSUE THREAD

**Issue by jridgewell** [lodash/babel-plugin-lodash#96]
Re: https://github.com/lodash/babel-plugin-lodash/issues/95#issuecomment-233423655

```js
var _lodash = require('lodash');
var _lodash2 = _interopRequireDefault(_lodash);
```
Notice how we're importing all of `lodash` there? We're only using it for `memoize`... We should try running `babel-plugin-lodash` when we compile.

**Comment by jdalton** [comment]
YES!!!!

**Comment by megawac** [comment]
nice i could never get this to work when i tried https://github.com/lodash/babel-plugin-lodash/commit/d3de6716db1feb41713fb1a207b7d541efe91f9a
